### ISSUE TITLE
Drink any type of bottle water raise 1 C except the normal water.

### ISSUE THREAD

**Issue by iamsoNewBee** [kotmatross28729/EnviroMine-continuation#12]
And there is no item option for enviromine in config. (Have to copy the old one

**Comment by iamsoNewBee** [comment]
I used the old config which TempEffect is -1 for coldwater, but it raised my temp 0.3C.

**Comment by iamsoNewBee** [comment]
Strange. I will check it tomorrow.

**Comment by kotmatross28729** [comment]
Oh no, wait, I think I see now: these options have a minimum value of 1, even though the default values ​​are correct. Therefore, forge reads exactly the minimum values, and not those in the config.

Sorry, this is really a mistake on my part and it really needs to be fixed

**Comment by kotmatross28729** [comment]
Should be fixed in 1.3.145. Delete `Global_Settings.cfg`, download 1.3.145, and recreate the config with the new version.
