### ISSUE TITLE
Mining enviromine coal ores doesnt release the related Hbm gas.

### ISSUE THREAD

**Issue by iamsoNewBee** [kotmatross28729/EnviroMine-continuation#15]
As the title, the vanilla one works correctly.

**Comment by iamsoNewBee** [comment]
And if it's possible to let devy light detect hbm gas block?

**Comment by kotmatross28729** [comment]
1) Do you mean coal dust?

2) Yes (via code)

**Comment by iamsoNewBee** [comment]
Yes. And now i can add the detectable items in config?

**Comment by iamsoNewBee** [comment]
Will you consider it for further update?

**Comment by kotmatross28729** [comment]
Yeah

**Comment by kotmatross28729** [comment]
https://github.com/user-attachments/assets/c0547466-1902-4792-b0c4-6aed33b34aff

**Comment by iamsoNewBee** [comment]
Thanks for your work very much. But in the issue i meat the enviromine coal, not the burning one. (Or are they already fixed?)

**Comment by kotmatross28729** [comment]
Yeah, and not burning too
