### ISSUE TITLE
HBM masks cant protect player from poisoning caused by the enviromine burning coal.

### ISSUE THREAD

**Issue by iamsoNewBee** [kotmatross28729/EnviroMine-continuation#16]
Only the enviromine one could do this.

**Comment by iamsoNewBee** [comment]
Oh, wow, I just need a more advanced one XD.

**Comment by kotmatross28729** [comment]
Enviromine's burning coal releases monoxide (like NTM nether coal). To protect against it, the gas mask must have resistance to monoxides
