### ISSUE TITLE
Issue with JameH2's fork of HBM NTM (version X5189_H261)

### ISSUE THREAD

**Issue by MrPhaot** [kotmatross28729/EnviroMine-continuation#18]
When I join the world with the newest version of NTM Space (X5189_H261) I get a crash. Looking at the log, I suspect it happens because of the temperature setting being broken by the update (which is confirmed by testing). Additionally, if the setting is turned on while **in** the world, it works fine.

**How to reproduce:**
1. Launch the minecraft with JameH2's fork of HBM NTM version X5189_H261
2. Join the world with Enviromine's body temperature setting on

The crash log:
[fml-client-latest.log](https://github.com/user-attachments/files/18245448/fml-client-latest.log)
[latest.log](https://github.com/user-attachments/files/18245449/latest.log)

**Comment by kotmatross28729** [comment]
Yeah, this has already been fixed in dev (partially). 

I don't have time to explain now, I'll change the comment later to clarify

(don't close it yet)

**Comment by MrPhaot** [comment]
No problem. It also happens if you join with any of the player options on however the game still crashes because of the temp check.

**Comment by kotmatross28729** [comment]
> No problem. It also happens if you join with any of the player options on however the game still crashes because of the temp check.

Most likely relates to 2 (see edited message above)

**Comment by kotmatross28729** [comment]
@MrPhaot , can you try this version: [envirodev.zip](https://github.com/user-attachments/files/18260134/envirodev.zip) ?

**Comment by MrPhaot** [comment]
It works! (At least with this version of the fork, there was an update)
![2024-12-28_12 24 44](https://github.com/user-attachments/assets/8cdc0f57-0969-4bec-baf4-9f91c25a921b)
