### ISSUE TITLE
Gravity causes thaumcraft leaves to behave like a normal block instead of leaves

### ISSUE THREAD

**Issue by xronin01** [kotmatross28729/EnviroMine-continuation#2]

**Comment by kotmatross28729** [comment]
Oh, you mean that thaumcraft leaves don't break when they reach the limit and just fall to the ground? Well, this is a problem with thaumcraft itself, the fact is that thaumcraft leaves do not have an oredict data on which based the finding of leaf blocks.
I'll try import the thaumcraft , and add its leaves as exception.
In the future, I’ll probably add a config in which you can specify whether the block is a leaf block, in case there is another mod that didn’t want to use ore dict

**Comment by kotmatross28729** [comment]
should work now:

https://github.com/kotmatross28729/EnviroMine-continuation/assets/110309314/fc44d4f3-11de-4e21-89fb-1624382624dc
