### ISSUE TITLE
Does the old configuration files work?

### ISSUE THREAD

**Issue by iamsoNewBee** [kotmatross28729/EnviroMine-continuation#6]
And does them (new and old) compat ?

**Comment by kotmatross28729** [comment]
I'm not exactly sure about this, the code is a complete mess and difficult to figure out, so I recommend using a new one (I'm not even exactly sure what the old config is, but all the configuration options added in this fork are in EM_ConfigHandler, which is probably considered a new config )

**Comment by iamsoNewBee** [comment]
I tested, it maybe compats. the two flies work together. (i added dimension option in the new config to disable the physics in the space. and it worked.)

**Comment by iamsoNewBee** [comment]
Does some hbm items (such as asbestos) affect air quality? And mechines (such as firebox) affect body temperature? I tested these and failed.

**Comment by kotmatross28729** [comment]
this is planned after full completion of ntm space compatibility
