### ISSUE TITLE
The sound of the gas mask is strange

### ISSUE THREAD

**Issue by iamsoNewBee** [kotmatross28729/EnviroMine-continuation#8]
It sounds like the player is constantly exhaling.

**Comment by kotmatross28729** [comment]
This is actually ["Darth Vader Breathing Sound"](https://soundeffects.fandom.com/wiki/Darth_Vader%27s_Breathing_Sound)

I don't know how weird it is, but you can change the sound using the resource pack - `assets/enviromine/sounds/gasmask.ogg`

As for the default sound, maybe when I refactor I'll find a better sound

**Comment by iamsoNewBee** [comment]
https://github.com/user-attachments/assets/b3990953-da20-41cf-8e2e-99881fea70aa

Hearing like this. I dont know what contributes this yet.

**Comment by kotmatross28729** [comment]
Hmm, it seems that the sound is looping incorrectly, but I fixed this bug a long time ago.

Also, do you have steps to reproduce? Because when I try now I can't reproduce

**Comment by iamsoNewBee** [comment]
It happens immediately without any other operations. I think it's a conflict problem because it works well itself.

**Comment by kotmatross28729** [comment]
Any news on the issue?
Have you found a conflicting mod?

**Comment by iamsoNewBee** [comment]
> Any news on the issue? Have you found a conflicting mod?

Sorry i was too busy thesedays so that i had forgot this. I may find out tonight.

**Comment by kotmatross28729** [comment]
@iamsoNewBee  (sorry for the ping), wanted to ask you if you have a problem with the PLSS breathing sound from NTM Space? It seems to use a pretty robust AudioWrapper system, instead of what is currently available in enviromine. Can you test with NTM Space and tell me?

**Comment by iamsoNewBee** [comment]
No problem with that.

**Comment by kotmatross28729** [comment]
Nice, then consider that this has already been fixed (all that remains is to implement it)

**Comment by kotmatross28729** [comment]
@iamsoNewBee (sorry for the ping again), can you try this version: [ENV_DEV.zip](https://github.com/user-attachments/files/18222900/ENV_DEV.zip)?

I added AudioWrapper support if HBM'S NTM is loaded, so audio should play fine with NTM

**Comment by kotmatross28729** [comment]
@iamsoNewBee (sorry for the ping again), can you try this version: [libs.zip](https://github.com/user-attachments/files/18223161/libs.zip) ?

I added AudioWrapper support if HBM'S NTM is loaded, so audio should play fine with NTM

**Comment by iamsoNewBee** [comment]
No need to say sorry and it is totally fixed : )
